# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:1.15
    restart: unless-stopped
    # маршрутизируем порты
    ports:
    - 80:80
    - 443:443
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
    - ./services/nginx:/etc/nginx/conf.d
    - ./www:/var/www
    - ./data/nginx:/var/log/nginx

  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: services/php
    restart: unless-stopped
    # монтируем директорию с проектами
    volumes:
    - ./www:/var/www

  memcached:
    image: bitnami/memcached:1.5.12
    ports:
      - 11111:11211
    volumes:
      - ./services/memcached/memcached.conf:/etc/memcached.conf
      - ./data/memcached/memcached.log:/var/log/memcached.log

  mariadb:
    image: mariadb:10.3
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
    - ./data/mariadb:/var/lib/mysql
    - ./www/sql/main.sql:/docker-entrypoint-initdb.d/01-main.sql
    environment:
      MYSQL_USER: anilibria
      MYSQL_PASSWORD: anilibria
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: anilibria

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
    - mariadb
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
    - 8080:80
    volumes:
    - ./services/phpmyadmin:/etc/phpmyadmin

  xbt_tracker:
    image: kauden/xbt_tracker:latest
#    volumes:
#      - ./images/xbt_tracker/xbt_tracker.conf:/opt/xbt_tracker/xbt_tracker.conf
    depends_on:
    - mariadb

  sphinx:
    build: services/sphinx
    restart: unless-stopped
    depends_on:
    - mariadb
    volumes:
      - ./data/sphinx:/var/log/sphinxsearch
#    - ./sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
#    - ./sphinxsearch:/var/lib/sphinxsearch/data
